config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "bikes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :pages, only: [:show]

  get "up" => "rails/health#show", as: :rails_health_check
  resources :bikes do
    resources :purchases, only: [:create, :show]
    resources :reviews, only: [:create, :show, :index]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :reviews

  has_one_attached :photo

  validates :model, :year, :description, :kilometers, :price, :category, presence: true
  validates :year, :kilometers, :price, numericality: true
  validates :year, comparison: { less_than_or_equal_to: 2024 }
  validates :kilometers, length: { maximum: 6 }
  validates :status, presence: true, inclusion: { in: %w(available sold) }
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User'
  belongs_to :bike
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
  belongs_to :bike
  validates :rating, :comment, :buyer, :seller, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bikes
  has_many :purchases
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @bikes = Bike.all
    if params[:query].present?
      sql_subquery = <<~SQL
      model ILIKE :query
      OR CAST(year AS TEXT) ILIKE :query
      OR (CAST(kilometers as TEXT) || ' km') ILIKE :query
      OR description ILIKE :query
      OR category ILIKE :query
      OR CAST(price AS TEXT) ILIKE :query
      SQL
      @bikes = @bikes.where(sql_subquery, query: "%#{params[:query]}%")

    end
  end
  def show
    @bike = Bike.find(params[:id])
    @purchase = Purchase.new
  end

  def new
    @bike = Bike.new
  end

  def create
    @user = current_user
    @bike = Bike.new(bike_params)
    @bike.user_id = @user.id
    if @bike.save
      redirect_to bike_path(@bike)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @bike = Bike.find(params[:id])
  end

  def update
    @bike = Bike.find(params[:id])
    @bike.update(bike_sold_params)
    redirect_to bike_path(@bike)
  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy
    redirect_to bikes_path, status: :see_other
  end

  private
  def bike_params
    params.require(:bike).permit(:model, :year, :description, :kilometers, :price, :category, :photo)
  end

  def bike_sold_params
    params.require(:bike).permit(:model, :year, :description, :kilometers, :price, :category, :photo, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    @bikes = current_user.bikes
    @purchases = current_user.purchases
    bikes_owned = Purchase.where(buyer_id: current_user.id)
    @bikes_purchased = Bike.where(id: bikes_owned.pluck(:bike_id))
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  def create

    @purchase = Purchase.new(purchase_params)
    @bike = Bike.find(@purchase.bike_id)
    @purchase.buyer_id = current_user.id

    if @purchase.save
      @bike.update(status: 'sold')
      redirect_to bike_purchase_path(@bike, @purchase), notice: 'Purchase was successfully created.'
    else
      render 'bikes/show', alert: "You are not logged in"
    end
  end

  def show
    @purchase = Purchase.find(params[:id])
    @bike = @purchase.bike  # to instance bike selling
    @seller = @bike.user # to instance seller
    @buyer = User.find(@purchase.buyer_id)
  end

  private

  def purchase_params
    params.require(:purchase).permit(:bike_id, :seller_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    # raise
    @bike = Bike.find(params[:bike_id])

    @reviews = Review.where(seller_id: @bike.user_id ) #se cambio para que muestre todo
    @bike.reviews

  end

  def create


    @review = Review.new(review_params)
    @bike = Bike.find(@review.bike_id)

    @review.buyer_id = current_user.id

    if @review.save
      redirect_to bike_reviews_path(@bike), notice: 'Review successfully added.'
    else
      @reviews = @bike.reviews
      render :index
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :buyer_id, :seller_id, :bike_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/edit.html.erb
<div class="container-img">
  <h1 class="title-img-new">Please enter the details of the bike you'd like to sell</h1>
  <%= simple_form_for @bike do |f| %>
    <div class="container" id="view-form" >
      <div class="row">
        <div class="row">
          <div class="col-lg-6 col-md-12">
            <%= f.input :model, label: "Bike Model", placeholder: @bike.model, input_html: { class: 'form-control' } %>
            <div class="row">
              <div class="col-6">
                <%= f.input :year, label: "Year", placeholder: @bike.year, input_html: { class: 'form-control' } %>
              </div>
              <div class="col-6">
                <%= f.input :kilometers, label: "Kilometers", placeholder: @bike.kilometers, input_html: { class: 'form-control' } %>
              </div>
            </div>
            <%= f.input :price, label: "Price", placeholder: @bike.price, input_html: { class: 'form-control' } %>
            <%= f.input :category, label: "Category", placeholder: @bike.category, collection: ["Naked", "Street", "Hybrid", "Electric", "Other"], prompt: "Select or create your own category", input_html: { class: 'form-control' } %>

            <div>
              <input type="text" class="d-none">
            </div>
          </div>
          <div class="col-lg-6 col-md-12 form-control-photo">
            <%= f.input :description, label: "Description", placeholder: @bike.description, input_html: { class: 'form-control', rows: 8 } %>
            <%= f.input :photo, as: :file, label: "Photo", input_html: { class: 'form-control-file' } %>
          </div>

        </div>
      <div class="row">
        <div class="d-flex justify-content-between mt-4">
            <%= link_to "Cancel", bikes_path, class: "backLink-show" %>
            <%= f.submit "Update Offer", class: "btn-show-bike-buy-1" %>
        </div>
      </div>

      </div>
    </div>
  <% end %>
</div>

</div>

app/views/bikes/index.html.erb
<section class="section__index">
  <div class="section__div--index-slogan">
    <div class="div__div--index-sloganTitle">
      <h2>The place to find
        <br>
        your next ride</h2>
        <%= link_to "Sell your bike", new_bike_path(@bike), class: "add-your-bike" %>
    </div>
  </div>

<div class="search-bar">
  <div class="search-bar-in">
    <%= form_with url: bikes_path, method: :get, class: "d-flex form-search-container" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-input",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "add-your-bike" %>
    <% end %>
  </div>
</div>


  <div class="container section__div--index-cards">
  <% if @bikes.empty? %>
    <h3 class="h3-none">There are no bikes that fit this description</h3>
  <% else %>
    <% @bikes.each do |bike| %>
      <% if bike.status == "available" %>
        <%= link_to bike_path(bike), class: "bike-a-details" do %>
          <div class="bike-card">
            <% if bike.photo.attached? %>
             <%= cl_image_tag bike.photo.key, class: "bike-image" %>
            <% else %>
              <%= image_tag "bike.jpg", class: "bike-image" %>
            <% end %>
            <div class="bike-details">
              <h3><%= bike.model %></h3>
              <p><%= bike.year %> &middot; <%= bike.kilometers %> km &middot; <%= bike.category %></p>
              <div class="bike-price">
                <p class="price">Precio contado</p>
                <p class="price-amount">$<%= bike.price %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  </div>
</section>

app/views/bikes/new.html.erb
<div class="container-img">
  <h1 class="title-img-new">Please enter the details of the bike you'd like to sell</h1>
  <%= simple_form_for @bike do |f| %>
    <div class="container" id="view-form" >
      <div class="row">
        <div class="row">
          <div class="col-lg-6 col-md-12">
            <%= f.input :model, label: "Bike Model", placeholder: "Include brand and model", input_html: { class: 'form-control' } %>
            <div class="row">
              <div class="col-6">
                <%= f.input :year, label: "Year", input_html: { class: 'form-control' } %>
              </div>
              <div class="col-6">
                <%= f.input :kilometers, label: "Kilometers", input_html: { class: 'form-control' } %>
              </div>
            </div>
            <%= f.input :price, label: "Price", placeholder: "In dolars", input_html: { class: 'form-control' } %>
            <%= f.input :category, label: "Category", placeholder: "select or create your own category", collection: ["Sport", "Naked", "Scooter", "Cruiser", "Enduro", "Other"], prompt: "Select or create your own category", input_html: { class: 'form-control' } %>

            <div>
              <input type="text" class="d-none">
            </div>
          </div>
          <div class="col-lg-6 col-md-12 form-control-photo">
            <%= f.input :description, label: "Description", input_html: { class: 'form-control', rows: 8 } %>
            <%= f.input :photo, as: :file, label: "Photo", input_html: { class: 'form-control-file' } %>
          </div>

        </div>
      <div class="row">
        <div class="d-flex justify-content-between mt-4">
            <%= link_to "Cancel", bikes_path, class: "backLink-show" %>
            <%= f.submit "Create Offer", class: "btn-show-bike-buy-1" %>
        </div>
      </div>

      </div>
    </div>
  <% end %>
</div>

</div>

app/views/bikes/show.html.erb
<section class="section__show">
  <div class="section__div-show">
    <div class="div__div-show-container-card">
      <h1 class="h1-show">
        <%= @bike.model %>, <%= @bike.year %>
      </h1>
      <div class="details-show-bike">
        <p class="details-text">
          <strong>Category:</strong> <%= @bike.category %>
        </p>
        <p class="details-text">
          <strong>Description:</strong> <%= @bike.description %>
        </p>
        <p class="details-text">
          <strong>Kilometers:</strong> <%= @bike.kilometers %> km
        </p>
        <p class="details-text">
          <strong>Price:</strong> $<%= @bike.price %>
        </p>
      </div>
      <!--<div class="details-text-user-post">
        <p class="details-text-user-post-p"><small>Posted by User ID: <%= @bike.user.email %></small></p>
      </div>-->
    </div>
  </div>
  <div class="section__div-show-img">
    <% if @bike.photo.attached? %>
      <%= cl_image_tag @bike.photo.key, :class => "photo-show-bike" %>
    <% else %>
      <%= image_tag "bike.jpg", :class => "photo-show-bike" %>
    <% end %>
  </div>
</section>
<div class="links-show-bike">
  <%= link_to "Back", bikes_path, :class => "backLink-show" %>
  <div class="links-show-bike-1">
    <% if user_signed_in? && current_user.id == @bike.user_id %>
    <%= link_to "Remove offer",
    bike_path(@bike.id),
    data: {turbo_method: :delete,
    turbo_confirm: "Are you sure?"},
    :class => "btn-show-bike-buy-1 margin-bottom-1" %>
    <%= link_to "Edit offer", edit_bike_path(@bike.id), :class => "btn-show-bike-buy-1" %>
  <% else %>
    <%= simple_form_for [@bike, @purchase] do |f| %>
      <%= f.hidden_field :seller_id, value: @bike.user_id %>
      <%= f.hidden_field :bike_id, value: @bike.id %>
      <%= f.submit "Buy", class: "btn-show-bike-buy" %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Habike</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'logo.webp' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/flashes" %>
  </body>

  <footer>
    <%= render "shared/footer" %>
    <%= yield :footer %>
  </footer>
</html>

app/views/pages/_posted.html.erb
<div class="container">
  <% bikes.each do |bike| %>
      <%= link_to bike_path(bike), :class => "text-decoration-none" do %>
      <div class="bike-card">
        <% if bike.photo.attached? %>
          <%= cl_image_tag bike.photo.key, class: "bike-image" %>
        <% else %>
          <%= image_tag "bike.jpg", class: "bike-image" %>
        <% end %>
        <div class="bike-details">
          <h3><%= bike.model %></h3>
          <p><%= bike.year %> &middot; <%= bike.kilometers %> km &middot; <%= bike.category %></p>
          <div class="bike-price">
            <p class="price">Precio contado</p>
            <p class="price-amount">$<%= bike.price %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/_purchased.html.erb
<div class="container">
  <% bikes_purchased.each do |bike| %>
      <%= link_to bike_path(bike), :class => "text-decoration-none" do %>
      <div class="bike-card">
        <% if bike.photo.attached? %>
          <%= cl_image_tag bike.photo.key, class: "bike-image" %>
        <% else %>
          <%= image_tag "bike.jpg", class: "bike-image" %>
        <% end %>
        <div class="bike-details">
          <h3><%= bike.model %></h3>
          <p><%= bike.year %> &middot; <%= bike.kilometers %> km &middot; <%= bike.category %></p>
          <div class="bike-price">
            <p class="price">Precio contado</p>
            <p class="price-amount">$<%= bike.price %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/show.html.erb
<div data-controller="toggle">

  <div class="sidebar">
    <button id="posted" class="active" data-action="click->toggle#displayPosted" data-toggle-target="postedButton">Posted bikes</button>
    <button id="purchased" data-action="click->toggle#displayPurchased" data-toggle-target="purchasedButton">Purchased bikes</button>
  </div>

  <section class="section-purchase">
    <div class="cards p-1" data-toggle-target="postedBikes">
      <%= render "posted", bikes: @bikes%>
    </div>
  
    <div class="cards p-1 d-none" data-toggle-target="purchasedBikes">
      <%= render "purchased", bikes_purchased: @bikes_purchased%>
    </div>
  </section>
</div>

app/views/purchases/_offers.html.erb
<div class="d-flex flex-wrap justify-content-around">
  <% Bike.where(status: "available").sample(3).each do |bike| %>
    <%= link_to bike_path(bike), class: "bike-a-details" do %>

      <div class="bike-card">
        <% if bike.photo.attached? %>
          <%= cl_image_tag bike.photo.key, class: "bike-image" %>
        <% else %>
          <%= image_tag "bike.jpg", class: "bike-image" %>
        <% end %>

        <div class="bike-details">
          <h3><%= bike.model %></h3>
          <p><%= bike.year %> &middot; <%= bike.kilometers %> km &middot; <%= bike.category %></p>
          <div class="bike-price">
            <p class="price">Precio contado</p>
            <p class="price-amount">$<%= bike.price %></p>
          </div>
        </div>
      </div>
    <% end %>

  <% end %>

</div>

app/views/purchases/_purchase_card.html.erb
<div class="row justify-content-center">
    <div class="bike-purchase-card">
      <div class="row mt-3 mb-t w-100">
        <h3  class="col-6">Purchase date:</h3>
        <p  class="col-6"><%= purchase.created_at.strftime("%d/%m/%Y") %></p>
      </div>

      <% if bike.photo.attached? %>
        <%= cl_image_tag bike.photo.key, class: "bike-image" %>
      <% else %>
        <%= image_tag "bike.jpg", class: "bike-image" %>
      <% end %>

      <div class="bike-purchase-details">
        <h3><%= bike.model %></h3>
        <p><%= bike.year %> &middot; <%= bike.kilometers %> km &middot; <%= bike.category %></p>
        <div class="bike-price-purchase">
          <p class="price">Precio contado</p>
          <p class="price-amount">$<%= bike.price %></p>

        </div>
        <div class="bike-price-purchase">
          <div class="container">
            <div class="col">
              <div class="row">
                <p class="price col-4">Seller email</p>
                <p  class="col-8">$<%= seller.email %></p>
              </div>
          <div class="row">
            <p class="price col-4">Buyer email</p>
                <p  class="col-8">$<%= buyer.email %></p>
          </div>
            </div>
          </div>
        </div>
      </div>
  </div>

</div>

app/views/purchases/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="row full-height">
      <div class="container p-3 mb-2 mt- border-bottom border-dark-gray">
        <div class="col justify-content-end">
          <%= link_to "Back", bikes_path, class: "btn btn-primary btn-lg backLink-show" %>
        </div>
      </div>
      <div class="row w-100">

        <div class="col-md-12 col-lg-6 text-center d-flex align-items-center justify-content-center">
          <div class="row mb-4">
            <h1 id="h1-sell">Let's go!</h1>
            <h3>Congratulations on your new Bike!</h3>
          </div>
        </div>
        <div class="col-md-12 col-lg-6">
          <%= render "purchase_card", purchase: @purchase, bike: @bike, seller: @seller, buyer: @buyer %>

        </div>
      </div>

    </div>
    <div class="col-12 mt-4">
        <div class="row border-bottom border-dark-gray mb-4">
          <h3>See Offers</h3>
        </div>
        <%= render "offers" %>
    </div>
  </div>
</div>

app/views/reviews/_new_review.html.erb
<h2>Add a new review</h2>
<%= simple_form_for([bike, Review.new]) do |f| %>
  <div class="form-group">
    <%= f.input :rating, as: :select, collection: 1..5, prompt: "Select a rating" %>
  </div>
  <div class="form-group">
    <%= f.input :comment, label: "Your comment" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :bike_id, value: bike.id %>
    <%= f.hidden_field :buyer_id, value: current_user.id %>
    <%= f.hidden_field :seller_id, value: bike.user.id %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit Review", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/_reviews_list.html.erb
<div class="row w-100 d-flex justify-content-center">
  <div class="col-md-8 col-12">
    <div class="card shadow-0 border" style="background-color: #f0f2f5;">
      <div class="card-body p-4 ">

        <% if reviews.any? %>
          <% reviews.each do |review| %>
            <div class="card mb-4">
              <div class="card-body">

                <p> <%= review.comment %></p>

                <div class="d-flex justify-content-between">
                  <div class="d-flex flex-row align-items-center">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(4).webp" alt="avatar" width="25" height="25" />
                    <p class="small mb-0 ms-2"><%= review.buyer.email %></p>
                  </div>
                  <div class="d-flex flex-row align-items-center">
                    <% review.rating.times do %>
                      <i class="fas fa-star text-warning mx-1"></i> <!-- Estrella llena -->
                    <% end %>

                    <% (5 - review.rating).times do %>
                      <i class="far fa-star text-muted mx-1"></i> <!-- Estrella vacía -->
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>No reviews available for this bike yet.</p>
        <% end %>



      </div>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="container mt-3 w-100">
  <div class="row w-100">
    <div class="row full-height">
      <div class="container p-3 mb-2 mt- border-bottom border-dark-gray">
        <div class="col justify-content-end">
          <%= link_to "Back", bikes_path, class: "btn btn-primary btn-lg backLink-show" %>
        </div>
      </div>
      <div class="row text-center mt-3 mb-4"><h1>Reviews for <%= @bike.user.email %></h1></div>
      <div class="row w-100 text-center">
        <div class="col-6">
          <% if current_user %>
            <%= render partial: "new_review", locals: { bike: @bike, current_user: current_user } %>
          <% end %>
        </div>
        <div class="col-6">

          <%= render "reviews_list", reviews: @reviews %>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<h2>Habike</h2>
<ul>
  <li><%= link_to 'Bikes', bikes_path %></li>
  <% if user_signed_in? %>
    <li><%= link_to 'Profile',  page_path(current_user.id) %></li>
  <% else %>
    <li><%= link_to "Login", new_user_session_path %></li>
  <% end %>
  <li><%= link_to 'Sell your Bike', new_bike_path(@bike) %></li>
</ul>
<div class="social-icons">
      <%= link_to 'https://www.instagram.com/motogp/', class: "fa fa-instagram", target: "_blank" do %>
      <% end %>
      <%= link_to 'https://x.com/motogp', class: "fa fa-twitter", target: "_blank" do %>
      <% end %>
  </div>
<p>&copy; Habike. All Rights Reserved.</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-habike">
  <div class="container-fluid">

    <div class="form-logo-h1">
    <%= link_to bikes_path, class: "navbar-brand" do %>
      <%= image_tag "logo.webp", class: "logo__img" %>
    <% end %>
      <h1>Welcome to HaBike</h1>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "profilepicme.jpeg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end dropdown-menu-transition" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", page_path(current_user.id), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item login-button-container">
            <%= link_to "Login", new_user_session_path, class: "nav-link login-button" %>
          </li>
          <li class="nav-item singup-button-container">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link singup-button" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'linksSingLogin' %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'linksSingLogin' %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'linksSingLogin' %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'linksSingLogin' %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: 'linksSingLogin' %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: 'linksSingLogin', data: { turbo: false } %><br />
  <% end %>
<% end %>